### ISSUE TITLE
Sublime 3 support?

### ISSUE THREAD

**Issue by chrisdrackett** [biermeester/Pylinter#27]
I'm getting the following after installing:

``` python

reloading plugin Pylinter.pylinter
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 869, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/cwd/Library/Application Support/Sublime Text 3/Packages/Pylinter/pylinter.py", line 78, in <module>
    if PYLINT_VERSION[0] == 0:
  IndexError: tuple index out of range

```

**Comment by biermeester** [comment]
Have you installed pylint? You can find it at http://www.pylint.org/

If you have installed it, what method did you use and what version? A clear error message if pylint isn't present wouldn't hurt either.

**Comment by goncalo** [comment]
I'm getting the same. pylint installed with pacman: https://www.archlinux.org/packages/extra/any/python-pylint/

```
reloading plugin Pylinter.pylinter
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 869, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/gcl/.config/sublime-text-3/Packages/Pylinter/pylinter.py", line 78, in <module>
    if PYLINT_VERSION[0] == 0:
IndexError: tuple index out of range
```

```
pylint --version
No config file found, using default configuration
pylint 1.0.0, 
astroid 1.0.0, common 0.60.0
Python 3.3.2 (default, May 21 2013, 15:40:45) 
[GCC 4.8.0 20130502 (prerelease)]
```

Also, after commenting out lines 49-75 in pylinter.py, I get the following when running the plugin:

```
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "/home/gcl/.config/sublime-text-3/Packages/Pylinter/pylinter.py", line 144, in run
    settings = self._read_settings()
  File "/home/gcl/.config/sublime-text-3/Packages/Pylinter/pylinter.py", line 178, in _read_settings
    python_path = PATH_SEPERATOR.join([str(p) for p in python_path])
TypeError: 'NoneType' object is not iterable
```

**Comment by biermeester** [comment]
I just pushed a new version. The problem should be gone. Please let me know if there are any more problems.

Thank you for your feedback!

**Comment by sputnikus** [comment]
Sorry for reopening, but I think this is related bug in latest release

``` python
Traceback (most recent call last):
  File "/opt/sublime_text_3/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/__init__.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 869, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/sputnikus/.config/sublime-text-3/Packages/Pylinter/pylinter.py", line 154, in <module>
    PYLINT_VERSION = PylSet.get_lint_version()
  File "/home/sputnikus/.config/sublime-text-3/Packages/Pylinter/pylinter.py", line 145, in get_lint_version
    os.path.dirname(PylSet.get_lint_path()),
  File "X/posixpath.py", line 151, in dirname
AttributeError: 'NoneType' object has no attribute 'rfind' 
```

**Comment by biermeester** [comment]
Hmm, I can't reproduce this on Ubuntu. Could you please make sure that the latest version of the Pylinter plugin is installed. If the problem remains, please set the following in `pylinter.py`: `PYLINTER_VERBOSE = True` and paste the console output here.

**Comment by sputnikus** [comment]
Pylinter doesn't want to use my configs and insists on getting pylint path on it's own. I've made you a pull request #28

**Comment by biermeester** [comment]
Thanks @sputnikus!
