### ISSUE TITLE
UnicodeDecode when source not ASCII only

### ISSUE THREAD

**Issue by Marrin** [biermeester/Pylinter#41]
The output of `pylint` is treated as ASCII only which is not true if the checked source code contains characters outside of ASCII.  At least at problematic places.

Simple test case:

``` python
# coding: utf-8
NAME='späm'
```

leads to the following in the ST console:

```
Writing file /home/bj/test.py with encoding UTF-8
************* Module test

Exception in thread Thread-46:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File "./pylinter.py", line 427, in run
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 96: ordinal not in range(128)
```

That line in `pylinter` reads:

``` python
        lines = [line for line in output.decode().split('\n')]  # pylint: disable=E1103
```

The output of `pylint` where decoding fails looks like this:

```
/home/bj/test.py:2:C0322:Operator not preceded by a space
NAME='späm'
    ^
```

**Comment by biermeester** [comment]
Thanks for the simple test case. It should be fixed now.
