### ISSUE TITLE
pylint run on save doesn't work after latest upgrade

### ISSUE THREAD

**Issue by thecodenomad** [biermeester/Pylinter#42]
Not sure what changed, but pylinter is no longer running with the latest update.

Sublime Text 3 - build 3059

**Comment by biermeester** [comment]
Can you set `verbose` to `true` in the Pylinter config and send me Pylinter's output?

**Comment by thecodenomad** [comment]
I'm not sure why it isn't finding the default pylint install

On first open:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 157, in on_api_ready
    m.plugin_loaded()
  File "/Users/autobot/Library/Application Support/Sublime Text 3/Packages/Pylinter/pylinter.py", line 71, in plugin_loaded
    PYLINT_VERSION = PylSet.get_lint_version()
  File "/Users/autobot/Library/Application Support/Sublime Text 3/Packages/Pylinter/pylinter.py", line 180, in get_lint_version
    startupinfo=STARTUPINFO)
  File "X/subprocess.py", line 818, in **init**
  File "X/subprocess.py", line 1416, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'pylint'

Subsequent saves:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "/Users/autobot/Library/Application Support/Sublime Text 3/Packages/Pylinter/pylinter.py", line 203, in run
    settings = PylSet.read_settings()
  File "/Users/autobot/Library/Application Support/Sublime Text 3/Packages/Pylinter/pylinter.py", line 143, in read_settings
    if PYLINT_VERSION[0] != 0:
TypeError: 'NoneType' object is not subscriptable

As for my installed pylint version:

rays-mbp:Frontier autobot$ pylint --version
No config file found, using default configuration
pylint 1.1.0, 
astroid 1.0.1, common 0.60.1
Python 2.7.5 (default, Sep  2 2013, 05:24:04) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)]

**Comment by thecodenomad** [comment]
Just as a workaround, set the pylint_path: <path to pylint> in the pylinter settings and this will get you back up and running.

**Comment by biermeester** [comment]
I added some old code back that will look for the `lint.py` module if the `pylint` executable is not found. I'm still somewhat puzzled why rrgomez' `pylint` was not picked up. Are there VirtualEnvs involved?

Anyway, thanks for the feedback, guys!

**Comment by thecodenomad** [comment]
Just an FYI on this, I wasn't using virtualenvs at all so yes, indeed, this is strange...

**Comment by xelnod** [comment]
Hello everyone!
I seem to have the same issue:
- PyLinter: Verbose is True
  Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "C:\Users\xelnod\AppData\Roaming\Sublime Text 3\Packages\Pylinter\pylinter.py", line 267, in run
    settings = PylSet.read_settings()
  File "C:\Users\xelnod\AppData\Roaming\Sublime Text 3\Packages\Pylinter\pylinter.py", line 151, in read_settings
    if PYLINT_VERSION[0] != 0:
  TypeError: 'NoneType' object is not subscriptable

(mdv_env) C:\Program Files\Sublime Text 3>pylint --version
No config file found, using default configuration
pylint-script.py 1.1.0,
astroid 1.0.1, common 0.61.0
Python 2.7.3 (default, Apr 10 2012, 23:31:26) [MSC v.1500 32 bit (Intel)]

any help for me? I'm somewhat new, maybe I'm doing something wrong

**Comment by iandanforth** [comment]
I had this issue when I first installed pylinter. It looks like plugin_loaded() is not being called until you restart sublime. After restart the global is populated properly and things work.
