### ISSUE TITLE
`UnboundLocalError` while searching for lint.py

### ISSUE THREAD

**Issue by littlemind** [biermeester/Pylinter#47]
I get the following error when Pylinter tries to find lint.py:

```
reloading plugin Pylinter.pylinter
 - PyLinter: Pylint executable *not* found
 - PyLinter: Seaching for lint.py module...
Traceback (most recent call last):
  File "/Applications/Sublime Text 3.app/Contents/MacOS/sublime_plugin.py", line 115, in reload_plugin
    m.plugin_loaded()
  File "/Users/christoph/Library/Application Support/Sublime Text 3/Packages/Pylinter/pylinter.py", line 77, in plugin_loaded
    DEFAULT_PYLINT_COMMAND = PylSet.get_default_pylint_command()
  File "/Users/christoph/Library/Application Support/Sublime Text 3/Packages/Pylinter/pylinter.py", line 207, in get_default_pylint_command
    if not pylint_path:
UnboundLocalError: local variable 'pylint_path' referenced before assignment
```

**Comment by biermeester** [comment]
Fixed. Thanks for the report.
