### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by jacebrowning** [biermeester/Pylinter#66]
This case seems to be unhandled when loading the version of pylint:

```
File "~/Library/Application Support/Sublime Text 3/Packages/Pylinter/pylinter.py", line 151, in read_settings
    if PYLINT_VERSION[0] != 0:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by xheisenbugx** [comment]
I am receiving the same error in sublime text 3 on Mac Os X

**Comment by siddrc** [comment]
Hi 
I am getting `TypeError: 'NoneType' object is not subscriptable` in my sublime text 3 console when I am trying to `Package Control:Install Package`
Here is the log
```
Package Control: Fetching list of available packages and dependencies
  Platform: windows-x64
  Sublime Text Version: 3126
  Package Control Version: 3.2.1
Exception in thread Thread-4:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "package_control.commands.install_package_command in C:\Users\horizzon\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 45, in run
  File "package_control.package_installer in C:\Users\horizzon\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 58, in make_package_list
  File "package_control.package_manager in C:\Users\horizzon\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 687, in list_available_packages
  File "package_control.package_manager in C:\Users\horizzon\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 551, in _list_available
  File "package_control.package_manager in C:\Users\horizzon\AppData\Roaming\Sublime Text 3\Installed Packages\Package Control.sublime-package", line 414, in list_repositories
TypeError: 'NoneType' object is not subscriptable
```

**Comment by ghost** [comment]
hi everybody, 
i'm using ST3 for a few days now and i like it. today i tried to install some new package via the built-in package manager, using the command  `Package Control: Install Package` and i recieved the following output:
```
Traceback (most recent call last): 

File "./python3.3/threading.py", line 901, in _bootstrap_inner 

File "package_control.commands.install_package_command in 
  .. /.config/.. /Package Control.sublime-package", line 45, in run

File "package_control.package_installer in 
  ... /.config/.. /Package Control.sublime-package", line 58, in make_package_list

File "package_control.package_manager in 
  .. /.config/.. /Package Control.sublime-package", line 694, in list_available_packages

File "package_control.package_manager in 
  .. /.config/.. /Package Control.sublime-package", line 554, in _list_available

File "package_control.package_manager in 
  .. /.config/.. /Package Control.sublime-package", line 414, in list_repositories

TypeError: 'NoneType' object is not subscriptable
```

i installed ST3 running as root, and most of time i use it, i'm running as root. could that cause issues? 

i remember when i used *code*  before, an (open-source-)editor by *visual studio*. there i had some problems running as root. in the end i uninstalled it, because i discovered it was sending a huge amount of data while running something in the background every time i was writing code. my connection and my os began slowing down. 
it seemed to me, that *microsoft* is using (or still testing on) a kind of encryption of personal data by storing the information in *json-files*. then, to decrypt it again, there are dozens and dozens of *JavaScript-files* needed, wich i found hidden inside a massive construct of directories and subdirectories and subsubdirectories ... , i'm talking about a few ten thousands of files, all created (and downloaded / recieved) by *vs-code*. 

i really tried everything ... first of all, i disabled the telemetry-setting in the "usual" prereferences. but that didn't change anything. so i looked for a file called '*product.json*', where i switched the telemetry-setting there to false, too. but i additionally had to switch another setting to false, called '*telemetry-crash-reporter*'. but all that had no effect as well. 
i even limited the permission to *vs-code* to access my network-interface by using *chmod* and *chown*. and first it seemed to work. 
unfortunately that didn't work fine very long and the editor started to bug around and crashing all the time wich was very anoying as i lost important parts of script sometimes while i was working on it. 
so i decided to uninstall it ... but even that wasn't as easy as i thought. 
and plus, i haven't installed it by *apt-get*, so i had to remove it by the (un-)installer from *vs-code* itself. 
but in the end i could remove it, but i think, i'll never use a program from *microsoft* again, even, when it is called open-source . . .
